name: snpmatch-5.0
channels:
    - bioconda
    - anaconda
    - conda-forge
    - defaults
dependencies:
    - python=3.7.6
    - numpy=1.17
    - scipy=1.4.1
    - pandas=1.0.5
    - hmmlearn=0.2.4
    - bcftools=1.9
    - scikit-allel=1.2.1
    - pip=20.1.1
    - r-base=3.6.0
    - r-rcpp 
    - r-qtl=1.44_9
    - pip:
        - "git+https://github.com/Gregor-Mendel-Institute/SNPmatch.git"
