name: snpmatch
channels:
    - bioconda
    - anaconda
    - conda-forge
    - defaults
dependencies:
    - python=3.7.6
    - pip=21.0.1
    - numpy=1.20
    - scipy=1.6.2
    - pandas=1.2.3
    - hmmlearn=0.2.5
    - scikit-allel=1.3.2
    - bcftools=1.12
    - r-base=4.0
    - r-qtl=1.48
    - pip:
        - "git+https://github.com/Gregor-Mendel-Institute/SNPmatch.git"
